name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: SmartCoder Code Review
        uses: xuxhing/code-review-action@v1.0.17
        with:
          GITHUB_TOKEN: ${{ github.token }}
          SMART_CODER_API_URL: ${{ vars.SMART_CODER_API_URL }}
          SMART_CODER_API_KEY: ${{ secrets.SMART_CODER_API_KEY }}
          exclude: "yarn.lock,dist/**"
