name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions: write-all

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
      - name: SmartCoder Code Review
        uses: xuxhing/code-review-action@v1.0.0-beta
